/*
# Create Contact Submissions Table
This script creates a new table `public.contact_submissions` to store messages sent through the website's contact form.

## Query Description:
This operation creates a new table and enables Row Level Security (RLS) to ensure data privacy. It is a non-destructive operation and will not affect any existing data.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true (by dropping the table)

## Structure Details:
- Table: `public.contact_submissions`
- Columns: `id`, `created_at`, `name`, `email`, `phone`, `company`, `inquiry_type`, `message`

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes. Adds policies to allow anonymous users to insert data, and gives full access to the `service_role` for management. This prevents anonymous users from reading, updating, or deleting submissions.
- Auth Requirements: None for insertion.

## Performance Impact:
- Indexes: A primary key index is automatically created on the `id` column.
- Triggers: None.
- Estimated Impact: Negligible performance impact.
*/

-- Create the table to store contact form submissions
CREATE TABLE public.contact_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name TEXT,
    email TEXT,
    phone TEXT,
    company TEXT,
    inquiry_type TEXT,
    message TEXT
);

-- Add a comment for the table for clarity in the Supabase dashboard
COMMENT ON TABLE public.contact_submissions IS 'Stores submissions from the website contact form.';

-- 1. Enable Row Level Security (RLS) on the table
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

-- 2. Create a policy that allows anonymous users to insert into the table.
-- This is required for the public-facing contact form to work.
CREATE POLICY "Allow anonymous inserts"
ON public.contact_submissions
FOR INSERT
TO anon
WITH CHECK (true);

-- 3. Create a policy that gives administrators (service_role) full access.
-- This allows you to view and manage the data from the Supabase dashboard or with your service key.
CREATE POLICY "Allow full access to service_role"
ON public.contact_submissions
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
